### ISSUE TITLE
What is this program licensed under?

### ISSUE THREAD

**Issue by mrHeavenli** [DaddyChucky/UNIVERSITY_SCRAPER#3]
I'm confused, you have the MIT License in the repository, yet at the bottom of README.md you have the line:
> COPYRIGHT: © DE LAFONTAINE, Charles. All Rights Reserved. Any distribution, idea or code replica, is strictly prohibited.

Although the MIT License allows distribution.
Could you perhaps be a bit clearer on how one may use your code?

**Comment by DaddyChucky** [comment]
You're 100% correct.
I need to discuss with some lawyers, and software engineers first in the scraping industry to release other versioning.
Normally, all my repositories are under the MIT License. I have only one other with Apache's license.
Although, for this scraping tool, I'm currently in discussion with lawyers & software engineers in the scraping industry to see if this repo is even allowed to exist.
I'll make changes soon... :)

**Comment by DaddyChucky** [comment]
> I'm confused, you have the MIT License in the repository, yet at the bottom of README.md you have the line:
> 
> > COPYRIGHT: © DE LAFONTAINE, Charles. All Rights Reserved. Any distribution, idea or code replica, is strictly prohibited.
> > Although the MIT License allows distribution.
> > Could you perhaps be a bit clearer on how one may use your code?

Alright, should be good now. Served under the MIT license.
Can't output / save on GitHub what I've scraped personally, that is releasing my "out" folder.
Have fun, and thank you again for this issue. Hope I've resolved it.

**Comment by mrHeavenli** [comment]
Okay, thanks for clearing that up :)
